### ISSUE TITLE
test issue: EOFError: Ran out of input

### ISSUE THREAD

**Issue by peterhuang621** [daooshee/QuadPrior#1]
您好，请问我复现时直接进行测试但是却出现以下报错怎么回事呢？环境安装之类和checkpoints都检查过了，谢谢啦
设备是NVIDIA GeForce RTX 3090 Ti

`(quadprior) hy2024@ubuntu-Super-Server:~/QuadPrior$ CUDA_VISIBLE_DEVICES=0 python test.py --input_folder ./test_data --same_folder ./output_QuadPrior
[2024-03-23 20:48:35,257] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
logging improved.
====== Load parameters ======
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Training ControlLDM as an unconditional model.
Loaded model config from [./models/cldm_v15.yaml]
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    state_dict = load_state_dict(
  File "/home/hy2024/QuadPrior/cldm/model.py", line 18, in load_state_dict
    state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
  File "/home/hy2024/miniconda3/envs/quadprior/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hy2024/miniconda3/envs/quadprior/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input`

**Comment by peterhuang621** [comment]
抱歉，才发现提供的代码里面的权重文件是空的。。。

**Comment by daooshee** [comment]
Sorry if my description was misleading. You should download the checkpoints from Google Drive or Baidu Disk and replace the empty files. Feel free to submit any issues if you have further questions :)

**Comment by hongjr03** [comment]
> Sorry if my description was misleading. You should download the checkpoints from Google Drive or Baidu Disk and replace the empty files. Feel free to submit any issues if you have further questions :)

Hi, the Google Drive link is empty. Would you mind updating the new link thx 😭

**Comment by daooshee** [comment]
> Hi, the Google Drive link is empty. Would you mind updating the new link thx 😭

Oops, sorry for my mistake. The google drive link is: https://drive.google.com/drive/folders/1NbqfOJYjv-_zH1NzTaaLmZDKjYA9clbd?usp=drive_link. I have also updated the README.
