### ISSUE TITLE
安装过程中遇到问题

### ISSUE THREAD

**Issue by Enternal-w** [daooshee/QuadPrior#11]
作者您好，AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
不知道该如何解决，一开始安装deepspeed0.13.1提示     from torch.distributed.elastic.agent.server.api import log, _get_socket_with_port
ImportError: cannot import name 'log' from 'torch.distributed.elastic.agent.server.api' (/home/vip/miniconda3/envs/quad/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py)
查阅后说是可以deepspeed升级到0.14.4但是就出现了 AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
目前不知道如何解决，求助作者

**Comment by wyn04** [comment]
@Enternal-w 你好！请问你是否解决了这个问题“AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'”？
