### ISSUE TITLE
The training process for the linear mapping W and the scale σ

### ISSUE THREAD

**Issue by yxx15** [daooshee/QuadPrior#3]
Hi, is the network for the linear mapping W and scale σ part pre-trained in the coco dataset? I didn't find the information in the training code. In line 240 of ciconv2d.py, I see the pre-trained model loaded, checkpoint file = '. /checkpoints/COCO-learnable_H_S_RGB_Order-Clean-T0Loss-30k.ckpt'

**Comment by daooshee** [comment]
Sorry that `ciconv2d.py` is a little bit messy. The linear mapping W is initialized by `torch.nn.Parameter(torch.tensor([[0.06,0.63,0.27],[0.3,0.04,-0.35],[0.34,-0.6,0.17]]))`, and the scale σ is predicted by the initialized `self.conv`. About `./checkpoints/COCO-learnable_H_S_RGB_Order-Clean-T0Loss-30k.ckpt`, it is actually a part of my debug code for visualization that I forgot to delete.
