### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by liwenchao0615** [daooshee/QuadPrior#6]
我是在win10环境上面跑的实验，说一下复现时可能会遇到的问题：
1、首先是basicsr，basicsr依赖torch和torchvision和tb-nightly，因为tb-nightly[清华源]不存在，安装时，如果使用单一源安装，由于原的包不完整性，容易导致安装失败，先用阿里源安装，然后再安装basicsr。
2、deepspeed的relearer的版本在win10环境下安装下载会存在问题，正常使用的版本是0.3.16。

**Comment by lyzcm** [comment]
问题1换阿里源可以直接解决

**Comment by daooshee** [comment]
Thank you for sharing your experience of setting up the environment on Win10!

**Comment by AAAeray** [comment]
> 我是在win10环境上面跑的实验，说一下复现时可能会遇到的问题： 1、首先是basicsr，basicsr依赖torch和torchvision和tb-nightly，因为tb-nightly[清华源]不存在，安装时，如果使用单一源安装，由于原的包不完整性，容易导致安装失败，先用阿里源安装，然后再安装basicsr。 2、deepspeed的relearer的版本在win10环境下安装下载会存在问题，正常使用的版本是0.3.16。

麻烦问下单张4090能训这个吗？
