### ISSUE TITLE
How to train the Bypass Decoder?

### ISSUE THREAD

**Issue by lyzcm** [daooshee/QuadPrior#7]
I successfully ran train.py by referring to the readme's guide, I set the resume_path to "", and was able to get the weights to be something like COCO-final.ckpt. 

But test.py also depends on Bypass Decoder's ckpt file and I'm not quite sure how it should be trained?

Thank you very much if you can provide more details.

**Comment by daooshee** [comment]
The ckpt of Bypass Decoder is `./checkpoints/main-epoch=00-step=7000.ckpt`, which can be downloaded from [Google Drive](https://drive.google.com/drive/folders/1NbqfOJYjv-_zH1NzTaaLmZDKjYA9clbd?usp=drive_link) or [Baidu Netdisk](https://pan.baidu.com/s/10sKrFyCHBQCVk76Y33wJlw?pwd=j9kv).

The training code of Bypass Decoder has not been released yet. It might take me some time to clean it.

**Comment by lyzcm** [comment]
I completely understand that refactoring the training code is a time-consuming process. This work has already shown great novelty and promising performance and I am excited to see the complete version of the training code 😊

**Comment by fanjunkai1** [comment]
> The ckpt of Bypass Decoder is `./checkpoints/main-epoch=00-step=7000.ckpt`, which can be downloaded from [Google Drive](https://drive.google.com/drive/folders/1NbqfOJYjv-_zH1NzTaaLmZDKjYA9clbd?usp=drive_link) or [Baidu Netdisk](https://pan.baidu.com/s/10sKrFyCHBQCVk76Y33wJlw?pwd=j9kv).
> 
> The training code of Bypass Decoder has not been released yet. It might take me some time to clean it.

Has the training code of Bypass Decode been released yet?

**Comment by yhhhyy** [comment]
Has the training code of Bypass Decode been released yet?

**Comment by yhhhyy** [comment]
@daooshee Has the training code of Bypass Decode been released yet?I urgently need it, thank you！

**Comment by liuxiangkai** [comment]
Has the training code of Bypass Decode been released yet?

**Comment by yhhhyy** [comment]
HHH收到，非常感谢
